### ISSUE TITLE
Possibly get rid of hard-coded DNS in the account file.

### ISSUE THREAD

**Issue by fkroener** [rembik/dehydrated-hetzner-hook#5]
Hi,

since the recent addition of CNAME support the hard-coded DNS IPs are even more an issue than they were before, since hetzner's DNS servers will refuse to answer for domains they aren't authoritative for, which means CNAME'd domains will mostly fail, unless one was to manually replace the first IP in the account file with a different DNS provider.

I wonder whether hard-coded DNS is actually necessary or improves anything upon doing the same thing Let's Encrypt does to check for propagation: resolve SOA/NS entries.

So, for checking CNAMEs one would best ask the locally configured DNS server and only for propagation checking the hetzner servers need to be queried, figuring out the IPs through DNS appears to be more flexible and future-proof than hard-coding.

Thanks again for your time and efforts.

**Comment by rembik** [comment]
Hey,

you can use this hook without the hard-coded DNS IPs, too. The propagation checking should be take a little bit longer, but works. Maybe this fix your CNAME resolving?

**Comment by rembik** [comment]
@fkroener did it worked out without dns servers in the account file?

**Comment by fkroener** [comment]
I'm quite sure it does, my issue is with hard-coding them without need where looking up SOA/NS would be more accurate and future-proof and in the case of non-hetzner CNAME domains would even result in faster verification. 

Or is there any reason to hard-code them? What if hetzner changes IPs? What about machines without IPv4 connectivity?

**Comment by rembik** [comment]
So you suggest to get the NS for propagation checking dynamically from the current zone file and use the local /etc/resolv.conf (default dnspython resolver nameservers) for CNAME checking?

**Comment by fkroener** [comment]
No, I'd suggest to drop the IPs from the config and get NS entries via DNS (possibly dnspython), similar to:
```
dig NS example.com

<snip>
;example.com.                   IN      NS

;; ANSWER SECTION:
example.com.            84351   IN      NS      robotns3.second-ns.com.
example.com.            84351   IN      NS      ns1.first-ns.de.
example.com.            84351   IN      NS      robotns2.second-ns.de.
<snip>
```
and then just query those.

NS for a CNAME entry should return the CNAME entry, so you'd need to request the NS again for the domain it is pointing at (which is then hopefully found in the robot domain listing as well).

But yeah, your local DNS resolver will know how to reach the domains returned for NS.

Alternatively (or in combination) you could use SOA and get the primary master to check for propagation of the tokens.

**Comment by rembik** [comment]
Would you please test the Pull request 'Dynamic dns with hotfix9' #13?

**Comment by fkroener** [comment]
Hello, thanks for having a look at this.

I'm getting the following error:
Sep 26 12:10:29 example.org dehydrated[2490]:  + Hetzner Robot hook executing: deploy_challenge
Sep 26 12:10:31 example.org dehydrated[2490]: Traceback (most recent call last):
Sep 26 12:10:31 example.org dehydrated[2490]:   File "/var/lib/dehydrated//hooks/hetzner/hook.py", line 431, in <module>
Sep 26 12:10:31 example.org dehydrated[2490]:     main(sys.argv[1:])
Sep 26 12:10:31 example.org dehydrated[2490]:   File "/var/lib/dehydrated//hooks/hetzner/hook.py", line 427, in main
Sep 26 12:10:31 example.org dehydrated[2490]:     ops[argv[0]](argv[1:])
Sep 26 12:10:31 example.org dehydrated[2490]:   File "/var/lib/dehydrated//hooks/hetzner/hook.py", line 375, in create_all_txt_records
Sep 26 12:10:31 example.org dehydrated[2490]:     args[i] = _check_dns_cname(args[i])
Sep 26 12:10:31 example.org dehydrated[2490]:   File "/var/lib/dehydrated//hooks/hetzner/hook.py", line 110, in _check_dns_cname
Sep 26 12:10:31 example.org dehydrated[2490]:     nameservers = _get_nameservers(get_tld('http://' + domain_cname[1]))

**Comment by rembik** [comment]
I refactored the code today. Please update the git branch and try again. 
I already tried it and it works like a charm for me. ;)

**Comment by fkroener** [comment]
Well, it's still failing here:

Sep 26 18:20:41 example.org dehydrated[26798]: Traceback (most recent call last):
Sep 26 18:20:41 example.org dehydrated[26798]:   File "/var/lib/dehydrated/hooks/hetzner/hook.py", line 425, in <module>
Sep 26 18:20:41 example.org dehydrated[26798]:     main(sys.argv[1:])
Sep 26 18:20:41 example.org dehydrated[26798]:   File "/var/lib/dehydrated/hooks/hetzner/hook.py", line 421, in main
Sep 26 18:20:41 example.org dehydrated[26798]:     ops[argv[0]](argv[1:])
Sep 26 18:20:41 example.org dehydrated[26798]:   File "/var/lib/dehydrated/hooks/hetzner/hook.py", line 372, in create_all_txt_records
Sep 26 18:20:41 example.org dehydrated[26798]:     args[i] = _check_dns_cname(args[i])  
Sep 26 18:20:41 example.org dehydrated[26798]:   File "/var/lib/dehydrated/hooks/hetzner/hook.py", line 112, in _check_dns_cname
Sep 26 18:20:41 example.org dehydrated[26798]:     fld = get_tld('http://' + domain_cname[1]) if domain_cname[1] else get_tld('http://' + domain_cname[0])
Sep 26 18:20:41 example.org dehydrated[26798]: TypeError: must be str, not bytes  

anything I might be doing wrong? this is with python3 btw.

**Comment by rembik** [comment]
Tested it on both, Python 3.5.2 and Python 2.7.12, and it works for me. Could you provide more information?
Do you have a special domain? Can you reinstall the requirements?

**Comment by fkroener** [comment]
requirements look fine here, I think I'm not doing anything special nor do I have any funny domains.

Setup is as follows:
example.org registered with hetzner, with only A entries for example.org and *.example.org and no TXT at all.
_acme-challenge.sub.domain.example.com with CNAME to _acme-challenge.example.org

The ordering appears to be:
sub.domain.example.com
example.org

with debug enabled I get:
DNS example.com => IPv4 [...]
CNAME _acme-challenge.sub.domain.example.com => _acme-challenge.example.org
and then the traceback starts.

Trying to cast the fld = get_tld(...) to string I get the following:
 fld = get_tld('http://' + str(domain_cname[1])) if domain_cname[1] else get_tld('http://' + str(domain_cname[0]))  
 File "/usr/x86_64-pc-linux-gnu/lib/python3.6/site-packages/tld/utils.py", line 222, in get_tld
    raise TldDomainNotFound(domain_name=domain_name)   
 tld.exceptions.TldDomainNotFound: Domain b'_acme-challenge.example.org' didn't match any existing TLD name! 

Hope this helps, if you need anything, please advise.

**Comment by rembik** [comment]
From my side it's difficult to say where the bug is. Maybe it was an unnecessary unicode encoding which could make trouble for same python3. Pls, check if its work now. I want to merge the pull request into master and release 1.1.0

**Comment by fkroener** [comment]
Looks great now, thanks! Either installing wheel or your changes to hook.py fixed it. Didn't bother to investigate.

Looking forward to 1.2.0!
