### ISSUE TITLE
Punycode Support

### ISSUE THREAD

**Issue by metaxmx** [rembik/dehydrated-hetzner-hook#6]
Hi,

If you have a domain name, which uses non-standard Unicode characters (like Umlauts), the "real" domain is encoded with so-called Punycode.
E.g. if you have the domain "münchen.de", it is really encoded as "xn--mnchen-3ya.de".
So, in order to use dehydrated, you have to enter the punycode version of the domain. However, in the Hetzner control panel, the Umlaut-Version is displayed.

It would be a great help, if this hook would detect and resolve Punycode in the given domains, before looking up the Hetzner Domain-ID when updating the zonefile.

**Comment by rembik** [comment]
Hi,
maybe you can fork this project, code the punycode check and make a pull request.

**Comment by rembik** [comment]
Hey @metaxmx and @mschaller,
the current master branch should fix this issue. Please give report, if it works for you, because I can not test it ([see code](https://github.com/rembik/dehydrated-hetzner-hook/blob/113d9e066de6bc9a9e5266e5b3eb3a69d94dff5f/hook.py#L684)).

**Comment by metaxmx** [comment]
Hi,
Everything works now as expected.
Thank you very much!
