### ISSUE TITLE
Support for wildcard certificates

### ISSUE THREAD

**Issue by level420** [rembik/dehydrated-hetzner-hook#7]
I'm not sure if this is possible already or planned, but it would be nice to have support for wildcard certificates with automatic renewal.

Do you have plans to support this?

Thank you for your efforts on this.

**Comment by rembik** [comment]
Its possible already.

**Comment by level420** [comment]
Yes! tested it. But it could be documented.

The main configs needed were in `/etc/dehydrated/config`:
```
CA="https://acme-v02.api.letsencrypt.org/directory"
CHALLENGETYPE="dns-01"
```
and in `/etc/dehydrated/domains.txt` :
```
yourdomain.tld *.yourdomain.tld
```

**Comment by rembik** [comment]
It is documented in the dehydrated repo  https://github.com/lukas2511/dehydrated . This hook only is builds upon this...

**Comment by level420** [comment]
Ah! I see. Thank you @rembik
