### ISSUE TITLE
Bug: hook fails while wildcard is set in zonefile

### ISSUE THREAD

**Issue by pp0815** [rembik/dehydrated-hetzner-hook#9]
As described [here](https://github.com/rembik/dehydrated-hetzner-hook/issues/8) (see last posts) the hook is failing, while a wildcard entry is set in the zonefile. 

It's possible to new or renew manually with certbot while keeping the wildcard inside the zonefile.

Thanks a lot for your time and efforts.

I'm not able to fix this myself, because my python is very poor, sorry.

**Comment by rembik** [comment]
Would you please test the Pull request 'Dynamic dns with hotfix9' #13?

**Comment by pp0815** [comment]
Tested: up and runnig without any problems! 

Thank you very much! Great work! :+1: :-)

```
/opt/dehydrated-hetzner-hook # git status
On branch dynamic-dns-with-hotfix9
Your branch is up-to-date with 'origin/dynamic-dns-with-hotfix9'.
```

```
/opt/dehydrated # git status
On branch master
Your branch is up-to-date with 'origin/master'.
```

**Comment by pp0815** [comment]
Just for information: if the zonefile is set without any entry for `_acme-challenge` and the wildcard entry ist set to

```
www IN A 1.2.3.4
* IN CNAME www
```

the script responses (as expected) with

`www IN TXT "MNBP0UaiBzXXXErVXyPw9K4omVqr6fP_V5aaMq_tz9o"`

instead of any _acme-challenge call. But all is working fine. :-)

Indeed there is no need to set an `_acme-challenge` entry as mentioned in `zones/example.com.txt` when using this wildcard definition.
